/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TicTacToeGame;

import java.awt.Color;

/**
 *
 * @author clatulip
 */
public class PlayerEntryDialog extends javax.swing.JFrame {
    private GameDataModel myModel;
    private GameController myController;
    
    /**
     * Creates new form PlayerEntryDialog
     */
    public PlayerEntryDialog(GameDataModel myModel, GameController myController) {
        this.myModel = myModel;
        this.myController = myController;
        initComponents();
        getContentPane().setBackground(new Color(121, 208, 195));
        if (!myModel.isTwoPlayers()) {
            // disable second player controls
            jLabelP2.setEnabled(false);
            jTextP2Name.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelP1 = new javax.swing.JLabel();
        jTextP1Name = new javax.swing.JTextField();
        jLabelP2 = new javax.swing.JLabel();
        jTextP2Name = new javax.swing.JTextField();
        jButtonStartGame = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Enter Player Information");

        jLabelP1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelP1.setText("Player 1:");

        jTextP1Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextP1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextP1NameActionPerformed(evt);
            }
        });

        jLabelP2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelP2.setText("Player 2:");

        jTextP2Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButtonStartGame.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonStartGame.setText("Start Game");
        jButtonStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartGameActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelP1)
                    .addComponent(jLabelP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextP2Name, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jTextP1Name))
                .addContainerGap(455, Short.MAX_VALUE))
            .addComponent(jLabelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextP1Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelP1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextP2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelP2))
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextP1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextP1NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextP1NameActionPerformed

    private void jButtonStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartGameActionPerformed
        // TODO add your handling code here:
        if (!jTextP1Name.getText().isEmpty()) {
            myModel.addNewPlayer(jTextP1Name.getText());
        }
        if (myModel.isTwoPlayers() && !jTextP2Name.getText().isEmpty()) {
            myModel.addNewPlayer(jTextP2Name.getText());
        }
        if (myModel.isGameReady()) {
            this.dispose();
            myController.startGame();
        } 
    }//GEN-LAST:event_jButtonStartGameActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        StartScreen myStartScreen = new StartScreen(myModel, myController);
        myStartScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonStartGame;
    private javax.swing.JLabel jLabelP1;
    private javax.swing.JLabel jLabelP2;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JTextField jTextP1Name;
    private javax.swing.JTextField jTextP2Name;
    // End of variables declaration//GEN-END:variables
}
