/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TicTacToeGame;

import java.awt.Color;

/**
 *
 * @author clatulip
 */
public class StartScreen extends javax.swing.JFrame {

    private GameDataModel myModel;
    private GameController myController;
    /**
     * Creates new form StartScreen
     */
    public StartScreen(GameDataModel myModel, GameController myController) {
        this.myModel = myModel;
        this.myController = myController;
        initComponents();
        getContentPane().setBackground(new Color(121, 208, 195));
        // for when user presses back button
        if (myModel.selectedGameMode()) {
            if (myModel.isTwoPlayers()) {
                jRadioButtonTwoPlayers.setSelected(true);
            } else {
                jRadioButtonPlayComputer.setSelected(true);
            }
            jPlayButton.setEnabled(true);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playType = new javax.swing.ButtonGroup();
        jLabelWelcome = new javax.swing.JLabel();
        jLabelSelect = new javax.swing.JLabel();
        jRadioButtonTwoPlayers = new javax.swing.JRadioButton();
        jRadioButtonPlayComputer = new javax.swing.JRadioButton();
        jPlayButton = new javax.swing.JButton();
        jLabelMyName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelWelcome.setFont(new java.awt.Font("Myanmar Text", 2, 48)); // NOI18N
        jLabelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcome.setText("Welcome to TicTacToe!");

        jLabelSelect.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelSelect.setText("Select an option below:");

        playType.add(jRadioButtonTwoPlayers);
        jRadioButtonTwoPlayers.setFont(new java.awt.Font("Myanmar Text", 0, 24)); // NOI18N
        jRadioButtonTwoPlayers.setText("Two Players");
        jRadioButtonTwoPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTwoPlayersActionPerformed(evt);
            }
        });

        playType.add(jRadioButtonPlayComputer);
        jRadioButtonPlayComputer.setFont(new java.awt.Font("Myanmar Text", 0, 24)); // NOI18N
        jRadioButtonPlayComputer.setText("Play against the Computer");
        jRadioButtonPlayComputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPlayComputerActionPerformed(evt);
            }
        });

        jPlayButton.setFont(new java.awt.Font("Myanmar Text", 0, 24)); // NOI18N
        jPlayButton.setForeground(new java.awt.Color(0, 153, 153));
        jPlayButton.setText("Play!");
        jPlayButton.setEnabled(false);
        jPlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlayButtonActionPerformed(evt);
            }
        });

        jLabelMyName.setText("Brought to you by Jessica Russ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelSelect))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(jLabelMyName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonTwoPlayers)
                            .addComponent(jRadioButtonPlayComputer))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMyName)
                .addGap(26, 26, 26)
                .addComponent(jLabelSelect)
                .addGap(36, 36, 36)
                .addComponent(jRadioButtonTwoPlayers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPlayComputer, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jPlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonTwoPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTwoPlayersActionPerformed
        // TODO add your handling code here:

        jPlayButton.setEnabled(true);
        myModel.setTwoPlayers(true);
        
    }//GEN-LAST:event_jRadioButtonTwoPlayersActionPerformed

    private void jRadioButtonPlayComputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPlayComputerActionPerformed
        // TODO add your handling code here:
        jPlayButton.setEnabled(true);
        myModel.setTwoPlayers(false);
    }//GEN-LAST:event_jRadioButtonPlayComputerActionPerformed

    private void jPlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlayButtonActionPerformed
        // now get players
        PlayerEntryDialog getPlayers = new PlayerEntryDialog(myModel, myController);
        getPlayers.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jPlayButtonActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMyName;
    private javax.swing.JLabel jLabelSelect;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JButton jPlayButton;
    private javax.swing.JRadioButton jRadioButtonPlayComputer;
    private javax.swing.JRadioButton jRadioButtonTwoPlayers;
    private javax.swing.ButtonGroup playType;
    // End of variables declaration//GEN-END:variables
}
